name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [esp32, esp32c3]
        display: [cu2, cu3]
        custom: [std]
        include:
          - target: esp32
            display: cu3
            custom: mike
          - target: esp32
            display: cu3
            custom: wroom2xrelay
          - target: esp32
            display: cu2
            custom: gpu7990
          - target: esp32
            display: cu3
            custom: gpu7990
          - target: esp32
            display: cu2
            custom: dvjcodec
          - target: esp32
            display: cu3
            custom: dvjcodec
          - target: esp32c3
            display: cu2
            custom: supermini
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    # We should be able to use SDKCONFIG_DEFAULTS, but it seems to be broken, this also works.
    # The echo makes sure there is a newline inbetween the original, and added part
    - run: echo >> sdkconfig.defaults.${{ matrix.target }}; cat sdkconfig.${{ matrix.display }} >> sdkconfig.defaults.${{ matrix.target }}

    - if: ${{ matrix.custom != 'std' }}
      run: echo >> sdkconfig.defaults.${{ matrix.target }}; cat sdkconfig.${{ matrix.custom }} >> sdkconfig.defaults.${{ matrix.target }}

    # Show used config
    - run: cat sdkconfig.defaults.${{ matrix.target }}

    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: latest
        target: ${{ matrix.target }}
        path: ''

    - uses: actions/upload-artifact@v3
      with:
        name: firmware-${{ matrix.target }}-${{ matrix.display }}-${{ matrix.custom }}
        path: |
          ${{ github.workspace }}/build/bootloader/bootloader.bin
          ${{ github.workspace }}/build/partition_table/partition-table.bin
          ${{ github.workspace }}/build/ion1-nowifi.bin
          ${{ github.workspace }}/sdkconfig
